### PR TITLE
Create registration.php

### PR DESCRIPTION
**Pull request by in-session**
Magento components, including modules, themes, and language packages, must be registered in the Magento system through the Magento ComponentRegistrar class.

https://devdocs.magento.com/guides/v2.3/extension-dev-guide/build/component-registration.html

### CODE REVIEW

**Comment by wigman** [comment]
The registration file exists in the ‘src’ directory.
The composer file references the ps4 loader to src/registration.php plus Magento automatically grubs all directories for registration files.

We use this src subdirectories to separate source-code from tests or 3rd party code like libraries/SDKs.

**Comment by in-session** [comment]
But we get an error message no module name in /setup/index.php#/module-grid, also the module is not disable. Could you check again

**Comment by wigman** [comment]
Did you install through composer? Or did you copy it to app/code?
What is your Magento version?

**Comment by in-session** [comment]
with composer, magento 2.3.5

**Comment by wigman** [comment]
Okay, we’ll check. We have registration inside src dir in all composer modules, so that in itself won’t be the problem.
Either something’s off, or there’s an issue with you particular install.

To be sure, you did run ‘bin/magento setup:upgrade’ after ‘composer install’?

**Comment by in-session** [comment]
Yes, has already been done several times

**Comment by schmengler** [comment]
> But we get an error message no module name in /setup/index.php#/module-grid, also the module is not disable. Could you check again

You are using the web installer? We never work with that, and I'd strongly discourage from doing so. Maybe there lies the problem

**Comment by in-session** [comment]
Sorry for the late feedback, problem found on APCu/OPCache Cache

**Pull request closed without merging**
